### ISSUE TITLE
Trakt Sync failing intermittently

### ISSUE THREAD

**Issue by github-gitlab** [michaldrabik/showly#898] opened 2024-12-01 18:17 UTC
**Describe the bug**
Today I checked last sync and it was done on Nov 19th despite auto sync enabled .  I tried doing it manually and it was failing every time. I logged out and in with trakt and still it was failing.

I logged out again and reinstalled the app and the first sync was successful. But after that it was again failing.

This same thing has happened before as well on previous versions.

**Expected behavior**
Auto and manual sync should be successful

I'm on the latest version 3.41, downloaded from IzzyonDroid. I'm currently using A15.

**Comment by michaldrabik** [comment] 2024-12-02 07:23
Is this something you can recreate everytime. If you would have tried reinstalling the app again today would the same thing happen with 1st sync going OK and following ones failing?

**Comment by RowanBee** [comment] 2024-12-19 17:00
I'm also having a sync fail. 3.41, izzyondroid. It says sync failed every time, however it is actually syncing to trakt tv.

**Comment by Kelvino9** [comment] 2024-12-27 12:11
Again the same with 3.42. Works good with a fresh install. But fails after some time.

**Comment by michaldrabik** [comment] 2024-12-27 14:37
That is quick sync feature in particular that's misbehaving right?

**Comment by Kelvino9** [comment] 2024-12-27 14:42
Yes, Instant Sync is enabled. When I open Showly or mark a show watched it happens.

**Comment by michaldrabik** [comment] 2024-12-27 15:16
If there are are any particualr actions that you guys are doing to get this error with Instant Sync it would be helpful to know. For example if you check many episodes at once, check/uncheck before sync runs etc. or is it just a basic check of a single episode then wait for sync which results in error and actually data being sent to Trakt anyway.

**Comment by michaldrabik** [comment] 2024-12-27 15:24
Might also be helpful to know if this is only for episodes or movies or it does not matter.

**Comment by michaldrabik** [comment] 2024-12-27 16:13
ℹ️ Since I do not see anything standing out and kind of walking in a dark here I have prepared an updated APK. It is basically the same as latest Github release but instead of displaying generic error message in notification it will display the original error dump.

It would be helpful if anyone that experiences this issue could install the update and report next time the error notification appears for Instant Sync. Should be the fastest way to pinpoint this.

* adding as ZIP as Github does not allow APKs
[showly-oss-release.zip](https://github.com/user-attachments/files/18261994/showly-oss-release.zip)

**Comment by Kelvino9** [comment] 2024-12-27 20:07
I get "Instant Sync failed." while launching the app, while syncing a single TV show and with a single movie.

With build 841 I still have the same issue as with 840, only difference ist the extended error message with "Required value 'deleted' missing at $"

**Comment by michaldrabik** [comment] 2024-12-28 07:55
> With build 841 I still have the same issue as with 840, only difference ist the extended error message with "Required value 'deleted' missing at $"

That's already a good hint for me

**Comment by michaldrabik** [comment] 2024-12-28 12:29
I located the problem and this should now be **_solved_**

Feel free to test with below APK before the release:

[app-release.zip](https://github.com/user-attachments/files/18266141/app-release.zip)

**Comment by Kelvino9** [comment] 2024-12-28 13:08
I can happily attest that the initial app launch and synching a single tv episode didn't cause any errors. So far build 842 seems to work as intended.

I'll observe it further and report back if there are any further issues.

Thank you very much for your assistance and continuous dedication on Showly.

**Comment by michaldrabik** [comment] 2024-12-28 21:47
The fix is now live: https://github.com/michaldrabik/showly/releases/tag/3.43.0

Closing the issue but please feel free to reopen new issue if anything else comes up.

**Closed by michaldrabik** 2024-12-28 21:47 UTC

**Comment by Kelvino9** [comment] 2024-12-28 21:58
Thank you!
